### ISSUE TITLE
local SMB connection

### ISSUE THREAD

**Issue by ektoplasmo** [objective-see/LuLu#61] opened 2018-05-08 06:39 UTC
When LuLu enabled i fails to connect on a local SMB connection  , disabling while connecting  helps  !

Bug or feature ?

**Comment by heywoodlh** [comment] 2018-05-11 15:31
I have the same issue.

**Comment by arkitype** [comment] 2018-05-15 11:02
me too

**Comment by arkitype** [comment] 2018-05-15 11:04
Think this could be a dupe of #21

**Comment by objective-see** [comment] 2018-05-31 20:22
That was a bug - sorry!

This should be fixed in latest release: v0.9.5

**Closed by objective-see** 2018-05-31 20:22 UTC
