### ISSUE TITLE
Lulu breaks Microsoft Remote Desktop on macOS Sequoia

### ISSUE THREAD

**Issue by Hawkedon** [objective-see/LuLu#637] opened 2024-09-17 14:39 UTC
When enabling Lulu, after about 15 seconds with Microsoft Remote Desktop, I received the following error message:

>Your session ended because of a data encryption error. If this keeps happening, contact your network administrator for assistance.
>
>Error code: 0x407

Disabling Lulu fixed the problem. I never encountered this problem on macOS before Sequoia. Seems some updates in macOS Sequoia break Lulu.

**Comment by xorxoxor** [comment] 2024-09-17 14:58
I am having similar Problems since the update with SSH connections. I'm randomly getting disconnects. Yesterday I also had issues with stalling downloads via https. I can also confirm your RDP Issues.

**Comment by Hawkedon** [comment] 2024-09-17 16:13
Seems there are quite a bit of change for network filtering in Sequoia. For example, this initializer has been deprecated

>https://github.com/objective-see/LuLu/blob/69b51f8da2c97d804998d55668a5d423fdb4a66d/LuLu/Extension/FilterDataProvider.m#L82

and replaced with

>https://developer.apple.com/documentation/networkextension/nenetworkrule/4360323-initwithremotenetworkendpoint

**Comment by anarchy89** [comment] 2024-09-17 23:47
I am getting drops for ssh (mac/linux), vnc(mac) and Remote Desktop for windows as well.

**Comment by sammcj** [comment] 2024-09-18 02:34
Out of interest - if you temporarily disable macOS's inbound firewall - does it resolve the issue?

**Comment by jdwhite** [comment] 2024-09-18 03:16
> Out of interest - if you temporarily disable macOS's inbound firewall - does it resolve the issue?

Yes, it does. It very much does.

Name of this issue should be renamed to  "Lulu breaks _**networking**_ on macOS Sequoia" except it's not really Lulu. Point is it's not just Remote Desktop. I first noticed it with SSH. Then my Zoom calls were dropping several seconds of audio randomly while others sharing the same internet pipe were entirely unaffected.

**Comment by sammcj** [comment] 2024-09-18 03:31
Ok, I’m not surprised. I have a theory that Apple hosed the packet filtering stack and it’s causing problems for a _lot_ of applications.

I can reproduce the problems without any third party packet filter - as I can the workaround.

**Comment by FideliusFalcon** [comment] 2024-09-18 13:05
I have simular issues with MacOS Sequoia, but I have general DNS resolve issues mostly in Firefox. 
It seems like the solution is either disabling LuLu (and other packet filtering tools) or disabling the build in Firewall on MacOS.

**Comment by andrey-admin** [comment] 2024-09-19 14:00
any fix available?

**Comment by FideliusFalcon** [comment] 2024-09-19 14:03
@andrey-admin Disable LuLu or Host Firewall until Apple fixes this

**Comment by hellpf** [comment] 2024-09-19 20:33
Just use ethernet instead of wifi + off firewall and it works just fine 🤷‍♂️

**Comment by objective-see** [comment] 2024-09-19 20:36
This has now been confirmed, to yes, be due to an Apple bug in macOS 15, that is widely impacting many 3rd-party security tools, that then in turn causes macOS networking to break.

This has been reported to Apple (and was so before macOS 15 was released), who have confirmed the issue and are hopefully working on a fix.

More info: "[Apple’s new macOS Sequoia update is breaking some cybersecurity tools](https://techcrunch.com/2024/09/19/apples-new-macos-sequoia-update-is-breaking-some-cybersecurity-tools/)"

**Comment by jdwhite** [comment] 2024-09-19 20:40
> Just use ethernet instead of wifi + off firewall and it works just fine 🤷‍♂️

If I'm correcting parsing this as use (ethernet + enabled firewall) instead of (wifi + disabled firewall), then no -- it does not work just fine.

Obviously, I can only speak for me but the network interface I used on my M1 MPB did not matter. I tried WiFi, an external 10GB adapter (OWC), and even the virtual interfaces between my host and guest machines in UTM! SSH connections on any of these interfaces would fail miserably.  FYI/FWIW.

**Comment by iplotin** [comment] 2024-10-06 18:06
Yes, APPLE left everyone in 15.x without a firewall, even their own. Looks like apple is not on the side of security and this was done intentionally. Apple does not equal security.

**Comment by wdormann** [comment] 2024-10-08 15:15
> Just use ethernet instead of wifi + off firewall and it works just fine 🤷‍♂️ (for me)

Wired ethernet is no better than Wi-Fi for me.  Even on wired, I get a Remote Desktop disconnect within minutes if LuLu and the macOS firewall are both enabled.
<img width="276" alt="Screenshot 2024-10-08 at 10 14 34 AM" src="https://github.com/user-attachments/assets/56d535da-b5be-483b-8149-730a63b801cf">

**Comment by bezzoh** [comment] 2024-10-18 07:29
Agreed. It happens equally with wired connections as it does WiFi. 
For me it occurs on 2x iMac M1's. One is wired, one is WiFi. It does not occur on my M3 MacBook Air.
"Just" turning off the firewall is not a fix. Thats like saying, "Just' leave your front door open because you've broke your key. "Just" - no.

**Comment by bezzoh** [comment] 2024-10-18 08:00
Well if you say so, I guess you could just ring all the various Cyber Insurance underwriters who insist that they're enforced to keep the premiums down then... 

In an enterprise environment, these are on by policy for such reasons. See we wont be paying an additional £10k on the policy, just so that we can turn this off...

**Comment by FideliusFalcon** [comment] 2024-10-18 08:11
If you work at an enterprise and have a device that is not rolled into a MDM, they don't care about endpoint security.

I'm pointing out that your analogy is wrong, not that every security policy is. 

I will stop replying now because it's out of scope of the original thread

**Comment by M4rt1n12** [comment] 2024-10-25 10:57
With the beta it actually works again.

**Comment by andrey-admin** [comment] 2024-10-29 10:18
Seems all fixed in macos 15.1

**Comment by anarchy89** [comment] 2024-10-29 10:30
Yup

On Oct 29, 2024, at 18:18, Andrey ***@***.***> wrote:

﻿

Seems all fixed in macos 15.1

**Closed** 2024-11-05 04:15 UTC
