### ISSUE TITLE
LuLu grabs focus from window

### ISSUE THREAD

**Issue by scorewinner** [objective-see/LuLu#112] opened 2018-11-22 14:31 UTC
When running, LuLu grabs the window focus every 3-5 seconds, no matter which program is running. It also is not showing any warning or message.

I am running MacOS Mojave Version 10.14 on a MacBook Pro 2017

**Comment by nicolaspte1998** [comment] 2018-11-24 14:50
Same to me, I uninstall LuLu at the moment.

**Comment by paymon23** [comment] 2018-11-30 09:02
This is happening to me too, killing the process in activity monitor is a temporary fix. Lulu appears to still do its job after that regardless but yeah, this is super annoying. Bug comes back every time you restart.

**Comment by JoshuaMSchultz** [comment] 2018-12-17 12:44
+1, killing processes on each startup for now.

**Comment by mchtt** [comment] 2018-12-19 11:31
+1 thx it explains why when I watch movies on a secondary screen, the mouse pointer appears over the video suddenly (because LULU is taking focus)

**Comment by JapanMark** [comment] 2019-01-11 20:20
Me too.That's caused by lulu helper,just open the LuLu preferences and wait a few seconds.

**Comment by acheype** [comment] 2019-01-21 12:17
I confirm the bug, really annoying. I hope a fix will be available soon :)

**Comment by objective-see** [comment] 2019-01-23 06:58
Looking into this.
Thanks for bug reports!

**Comment by guzelmarmara** [comment] 2019-01-28 23:03
I also encounter the same problem. Mojave on Macbook Pro 13" 2017 non-touch.

**Comment by Tsybanov** [comment] 2019-02-08 23:10
Just join everyone with the same problem

**Comment by objective-see** [comment] 2019-02-11 07:29
This should be fixed in version `1.2.0` 
...if you want to test the beta, and confirm, I'd be super appreciative!

https://bitbucket.org/objective-see/deploy/downloads/LuLu_1.2.0_BETA.zip

**Comment by paymon23** [comment] 2019-02-11 13:34
> This should be fixed in version `1.2.0`
> ...if you want to test the beta, and confirm, I'd be super appreciative!
> 
> https://bitbucket.org/objective-see/deploy/downloads/LuLu_1.2.0_BETA.zip

I can confirm that this particular bug is fixed with this update!
However, I've gotten a funny issue where I have two Lulu's appearing (please see screenshot link) - 

https://i.imgur.com/OypSdxV.png

Please let me know how I can fix this, I don't really want to uninstall Lulu fully (if that's a fix) because I don't want to lose my rule-set 😄

**Comment by objective-see** [comment] 2019-02-12 02:31
Ah, glad this bug was fixed!
...and just pushed a commit that should prevent two instances of two LuLu (login items) from running.

Build with this new fix: [https://bitbucket.org/objective-see/deploy/downloads/LuLu_1.2.0_BETA.zip](https://bitbucket.org/objective-see/deploy/downloads/LuLu_1.2.0_BETA.zip)

Please LMK if there are any other issues :)

**Comment by paymon23** [comment] 2019-02-12 09:07
Everything is working as expected now. Thank you for your work!
I'll keep you posted if anything else crops up :)

**Comment by objective-see** [comment] 2019-02-16 21:36
Thank you for your patience! 
Just [released](https://github.com/objective-see/LuLu/releases/tag/v1.2.0) version 1.2.0 which should resolve this issue.

Though please let me know if it still persists!

**Closed** 2019-03-04 02:02 UTC
