### ISSUE TITLE
Issue with content filters on MacOS Ventura 13.4 beta 4

### ISSUE THREAD

**Issue by danieltomasz** [objective-see/LuLu#536] opened 2023-05-03 07:20 UTC
Just to let  the developers know

https://forums.macrumors.com/threads/psa-latest-macos-ventura-13-4-beta-doesnt-play-nice-with-content-filter-apps.2388469/page-3https://forums.macrumors.com/threads/psa-latest-macos-ventura-13-4-beta-doesnt-play-nice-with-content-filter-apps.2388469/page-3

**Comment by lightumcc** [comment] 2023-05-03 10:16
The same issue

↓macOS Ventura 13.4 Beta 4 Release Notes
> Networking
> 
> Known Issues
> 
> Some network extensions quit unexpectedly, causing network connectivity issues. (108814599)
> 
> Workaround: Disable the firewall/network security application.

**Comment by BioXeon** [comment] 2023-05-03 14:32
I have the same after upgraded my MacOS to 13.4 Beta 4. 
Networking -> Filters -> Filters & Proxies -> com.objective-see.lulu.app
This issue makes my wireless/ethernet links are up and down, and so on indefinitely😆 
Workaround: Turn off it // I mean "com.objective-see.lulu.app"

**Comment by lightumcc** [comment] 2023-05-03 14:33
> I have the same after upgraded my MacOS to 13.4 Beta 4. 
> Networking -> Filters -> Filters & Proxies -> com.objective-see.lulu.app
> This issue makes my wireless/ethernet links are up and down, and so on indefinitely😆 
> Workaround: Turn off it // I mean "com.objective-see.lulu.app"

That's true

**Comment by einsteinbqat** [comment] 2023-05-05 15:23
I disabled Lulu for now

**Comment by RealZac** [comment] 2023-05-07 08:00
Indeed disabling LuLu works, but it's only a bad workaround. Any news with resolving the problem?
Can LuLu do anything at all? Or do we have to wait until Apple fixes this?

**Comment by lightumcc** [comment] 2023-05-07 09:12
> Indeed disabling LuLu works, but it's only a bad workaround. Any news with resolving the problem? Can LuLu do anything at all? Or do we have to wait until Apple fixes this?

I think we have to wait until Apple fix it because Apple marks this as an issue in the feedback assistant

**Comment by BioXeon** [comment] 2023-05-07 21:58
In my opinion they will wait until Apple releases stable edition of MacOS. After that if the issue isn’t solved they will start to do anything. Am I wrong @Lulu ?

**Comment by objective-see** [comment] 2023-05-08 10:47
Yes, as this is a (known) Apple issue, we have to wait until Apple fixes it 🤷🏻‍♂️

**Comment by Sebbo69** [comment] 2023-05-09 17:57
I think it is fixed with the new Beta 5. Download available

**Closed** 2023-05-16 13:28 UTC
